version: '3.8'
services:
  mollrang-dev-server:
    build:
      context: .
      dockerfile: dev-server.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - foody-db
  foody-db:
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foody
